services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: k1t

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  qr.kit:
    build: .
    restart: always
    ports:
      - 3242:3242
    command: ["/usr/local/bin/qr.kit/qr.kit"]

  kit:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    command: ["/usr/local/bin/kit", "kat"]
